name: musa-620
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - pip
  - altair
  - seaborn
  - vega_datasets
  - notebook
  - vega
  - geopandas
  - descartes
  - cartopy
  - mapclassify
  - contextily=1.0rc2
